# Generated by Django 6.1.2 on 2026-10-08 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0003_establecimiento_licencia_hasta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPlataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_prueba', models.PositiveIntegerField(default=7, verbose_name='días de prueba gratis')),
                ('instrucciones_pago', models.TextField(default='Realiza el pago por transferencia o Nequi y escribe la referencia del comprobante en tu solicitud. La licencia se activa en cuanto confirmemos el pago.', verbose_name='instrucciones de pago')),
                ('whatsapp', models.CharField(blank=True, help_text='Ej: 573001234567', max_length=20, verbose_name='WhatsApp de contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
            ],
            options={
                'verbose_name': 'configuración de la plataforma',
                'verbose_name_plural': 'configuración de la plataforma',
                'db_table': 'configuracion_plataforma',
            },
        ),
        migrations.CreateModel(
            name='PlanLicencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dias', models.PositiveIntegerField(verbose_name='días de duración')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='disponible para la venta')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Posición en la página de planes.')),
            ],
            options={
                'verbose_name': 'plan de licencia',
                'verbose_name_plural': 'planes de licencia',
                'db_table': 'planes_licencia',
                'ordering': ['orden', 'dias'],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del plan al momento de la compra. Vacío = precio actual del plan.', max_digits=10)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de comprobante, transferencia o Nequi que indicó el taller.', max_length=100, verbose_name='referencia de pago')),
                ('notas', models.TextField(blank=True, verbose_name='notas internas')),
                ('fecha_inicio', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='solicitada el')),
                ('aprobada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('aprobada_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='cuentas.establecimiento')),
                ('solicitada_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencias', to='licencias.planlicencia')),
            ],
            options={
                'db_table': 'licencias',
                'ordering': ['-creado_en'],
            },
        ),
    ]
