# Generated by Django 6.1.2 on 2026-10-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='código de barras')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('accesorio', 'Accesorio'), ('repuesto', 'Repuesto'), ('herramienta', 'Herramienta')], max_length=50, verbose_name='categoría')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=2, verbose_name='stock mínimo')),
                ('es_repuesto', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'producto',
                'db_table': 'productos_inventario',
                'ordering': ['nombre'],
            },
        ),
    ]
