# Generated by Django 6.1.2 on 2026-10-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_establecimiento_usuario_establecimiento'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinventario',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cuentas.establecimiento'),
        ),
        migrations.AlterField(
            model_name='productoinventario',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='código de barras'),
        ),
        migrations.AddConstraint(
            model_name='productoinventario',
            constraint=models.UniqueConstraint(fields=('establecimiento', 'codigo_barras'), name='productos_codigo_barras_unico'),
        ),
    ]
