# Generated by Django 6.1.2 on 2026-10-08 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_establecimiento_usuario_establecimiento'),
        ('ventas', '0003_asignar_establecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='cuentas.establecimiento'),
        ),
    ]
