# Generated by Django 6.1.2 on 2026-10-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre del taller')),
                ('nit', models.CharField(blank=True, max_length=30, null=True, verbose_name='NIT / documento')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='dirección')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'establecimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='cuentas.establecimiento'),
        ),
    ]
