# Generated by Django 6.1.2 on 2026-10-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_establecimiento_usuario_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='licencia_hasta',
            field=models.DateTimeField(blank=True, help_text='Al pasar esta fecha el taller queda bloqueado hasta renovar. Vacío = bloqueado.', null=True, verbose_name='licencia vigente hasta'),
        ),
    ]
