# Generated by Django 6.1.2 on 2026-10-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='documento')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='dirección')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dispositivo', models.CharField(choices=[('celular', 'Celular'), ('laptop', 'Laptop'), ('pc_escritorio', 'PC de escritorio'), ('tablet', 'Tablet')], max_length=30, verbose_name='tipo')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie_imei', models.CharField(blank=True, max_length=50, null=True, verbose_name='serie / IMEI')),
                ('clave_patron', models.CharField(blank=True, max_length=100, null=True, verbose_name='clave o patrón')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.cliente')),
            ],
            options={
                'db_table': 'equipos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
