# Generated by Django 6.1.2 on 2026-10-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('cuentas', '0002_establecimiento_usuario_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='cuentas.establecimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='documento'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('establecimiento', 'documento_id'), name='clientes_documento_unico'),
        ),
    ]
