# Generated by Django 6.1.2 on 2026-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='patron',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='patrón de desbloqueo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clave_patron',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='clave / PIN'),
        ),
    ]
