# Generated by Django 6.1.2 on 2026-10-08 07:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(editable=False, max_length=20, unique=True, verbose_name='código')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_diagnostico', 'En diagnóstico'), ('esperando_aprobacion', 'Esperando aprobación'), ('en_reparacion', 'En reparación'), ('listo_entrega', 'Listo para entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=30)),
                ('falla_reportada', models.TextField()),
                ('diagnostico_tecnico', models.TextField(blank=True, null=True, verbose_name='diagnóstico técnico')),
                ('observaciones_esteticas', models.TextField(blank=True, help_text='Rayones, golpes, falta de tornillos…', null=True, verbose_name='observaciones estéticas')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('costo_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_promesa', models.DateTimeField(blank=True, null=True, verbose_name='fecha prometida')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.equipo')),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'orden de servicio',
                'verbose_name_plural': 'órdenes de servicio',
                'db_table': 'ordenes_servicio',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFotografica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.CharField(choices=[('recepcion', 'Recepción'), ('proceso_tecnico', 'Proceso técnico'), ('entrega', 'Entrega')], max_length=20)),
                ('url_foto', models.ImageField(max_length=500, upload_to='evidencias/%Y/%m/', verbose_name='foto')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripción')),
                ('tomada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='ordenes.ordenservicio')),
            ],
            options={
                'verbose_name': 'evidencia fotográfica',
                'verbose_name_plural': 'evidencias fotográficas',
                'db_table': 'evidencias_fotograficas',
                'ordering': ['tomada_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReparacionRepuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.productoinventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='ordenes.ordenservicio')),
            ],
            options={
                'verbose_name': 'repuesto usado',
                'verbose_name_plural': 'repuestos usados',
                'db_table': 'detalle_reparacion_repuestos',
            },
        ),
    ]
