# Generated by Django 6.1.2 on 2026-10-08 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_establecimiento_alter_cliente_documento_id_and_more'),
        ('cuentas', '0002_establecimiento_usuario_establecimiento'),
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='cuentas.establecimiento'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='codigo_orden',
            field=models.CharField(editable=False, max_length=20, verbose_name='código'),
        ),
        migrations.AddConstraint(
            model_name='ordenservicio',
            constraint=models.UniqueConstraint(fields=('establecimiento', 'codigo_orden'), name='ordenes_codigo_unico'),
        ),
    ]
